// Solidigm Brand Tailwind Preset — generated by build.js
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "solidigm-purple": "#4f00b5",
        "light-purple": "#8d59cf",
        "dark-purple": "#2f006b",
        "ultra-dark-purple": "#160231",
        "dark-blue": "#00083f",
        "dark-grey": "#21201f",
        "black": "#000000",
        "white": "#ffffff",
        "light-gray": "#f5f3f1",
        "gray": "#a5a29d",
        "medium-gray": "#52514f",
        "electric-teal": "#00ffec",
        "electric-pink": "#ea11bc",
        "orange": "#ffa42c"
      },
      "fontFamily": {
        "sora": [
          "Sora",
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ]
      },
      "fontSize": {
        "dt-hero": [
          "112px",
          {
            "lineHeight": "110%",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-1": [
          "72px",
          {
            "lineHeight": "82px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-2": [
          "62px",
          {
            "lineHeight": "110%",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-3": [
          "42px",
          {
            "lineHeight": "48px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-4": [
          "32px",
          {
            "lineHeight": "38px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-5": [
          "24px",
          {
            "lineHeight": "28px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-headline-6": [
          "20px",
          {
            "lineHeight": "26px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-accordion": [
          "32px",
          {
            "lineHeight": "38px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-body": [
          "16px",
          {
            "lineHeight": "20px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-caption": [
          "14px",
          {
            "lineHeight": "18px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-category": [
          "10px",
          {
            "lineHeight": "14px",
            "letterSpacing": "2px",
            "fontWeight": "600"
          }
        ],
        "dt-button": [
          "10px",
          {
            "lineHeight": "14px",
            "letterSpacing": "2px",
            "fontWeight": "600"
          }
        ],
        "dt-disclaimer": [
          "12px",
          {
            "lineHeight": "14px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "dt-breadcrumb": [
          "10px",
          {
            "lineHeight": "14px",
            "letterSpacing": "2px",
            "fontWeight": "700"
          }
        ],
        "mb-hero": [
          "52px",
          {
            "lineHeight": "58px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-1": [
          "42px",
          {
            "lineHeight": "48px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-2": [
          "32px",
          {
            "lineHeight": "38px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-3": [
          "24px",
          {
            "lineHeight": "28px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-4": [
          "18px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-5": [
          "16px",
          {
            "lineHeight": "20px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-headline-6": [
          "14px",
          {
            "lineHeight": "18px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-accordion": [
          "18px",
          {
            "lineHeight": "22px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-body-1": [
          "14px",
          {
            "lineHeight": "18px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-caption": [
          "16px",
          {
            "lineHeight": "20px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-category": [
          "14px",
          {
            "lineHeight": "18%",
            "letterSpacing": "2px",
            "fontWeight": "600"
          }
        ],
        "mb-button-link": [
          "10px",
          {
            "lineHeight": "14px",
            "letterSpacing": "2px",
            "fontWeight": "600"
          }
        ],
        "mb-disclaimer": [
          "10px",
          {
            "lineHeight": "12px",
            "letterSpacing": "0px",
            "fontWeight": "200"
          }
        ],
        "mb-breadcrumb": [
          "10px",
          {
            "lineHeight": "16px",
            "letterSpacing": "2px",
            "fontWeight": "700"
          }
        ]
      }
    }
  }
};
