#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** "Solidigm Purple" → "solidigm-purple" */
function toKebab(name) {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

/** "Solidigm Purple" → "solidigmPurple", "DT Hero" → "dtHero" */
function toCamel(name) {
  const words = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return words
    .map((w, i) =>
      i === 0
        ? w.toLowerCase()
        : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    )
    .join('');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`  ✓ ${path.relative(process.cwd(), filePath)}`);
}

// ---------------------------------------------------------------------------
// Source token readers
// ---------------------------------------------------------------------------

function readSourceTokens() {
  function readJSON(name) {
    return JSON.parse(
      fs.readFileSync(path.join(__dirname, 'tokens', `${name}.json`), 'utf8')
    );
  }
  return {
    colorsRaw:     readJSON('colors'),
    typographyRaw: readJSON('typography'),
    spaceRaw:      readJSON('space'),
    breakpointsRaw:readJSON('breakpoints'),
    radiusRaw:     readJSON('radius'),
    shapeRaw:      readJSON('shape'),
    motionRaw:     readJSON('motion'),
    elevationRaw:  readJSON('elevation'),
    iconsRaw:      readJSON('icons'),
    semanticRaw:   readJSON('semantic'),
  };
}

// ---------------------------------------------------------------------------
// Transform: colors
// ---------------------------------------------------------------------------

/**
 * Returns a flat array of { name, kebab, camel, hex, group }
 * Skips gradient tokens.
 */
function transformColors(colorsRaw) {
  const colors = [];
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      colors.push({
        name,
        kebab: toKebab(name),
        camel: toCamel(name),
        hex: token.$value,
        group,
      });
    }
  }
  return colors;
}

// ---------------------------------------------------------------------------
// Transform: typography
// ---------------------------------------------------------------------------

/**
 * Returns a flat array of { name, kebab, camel, group, value }
 * where value contains fontFamily, fontSize, fontWeight, letterSpacing,
 * lineHeight, textTransform, textDecoration.
 */
function transformTypography(typographyRaw) {
  const styles = [];
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      styles.push({
        name,
        kebab: toKebab(name),
        camel: toCamel(name),
        group,
        value: { ...token.$value },
      });
    }
  }
  return styles;
}

// ---------------------------------------------------------------------------
// Generator: CSS Custom Properties
// ---------------------------------------------------------------------------

function generateCSS(colors, typography, outDir) {
  // colors.css
  let colorsCss = '/* Solidigm Brand Color Tokens — generated by build.js */\n:root {\n';
  for (const c of colors) {
    colorsCss += `  --solidigm-color-${c.kebab}: ${c.hex};\n`;
  }
  colorsCss += '}\n';
  writeFile(path.join(outDir, 'colors.css'), colorsCss);

  // typography.css
  let typeCss = '/* Solidigm Brand Typography Tokens — generated by build.js */\n:root {\n';
  for (const t of typography) {
    const k = t.kebab;
    const v = t.value;
    typeCss += `  --solidigm-type-${k}-font-family: ${v.fontFamily};\n`;
    typeCss += `  --solidigm-type-${k}-font-size: ${v.fontSize};\n`;
    typeCss += `  --solidigm-type-${k}-font-weight: ${v.fontWeight};\n`;
    typeCss += `  --solidigm-type-${k}-line-height: ${v.lineHeight};\n`;
    typeCss += `  --solidigm-type-${k}-letter-spacing: ${v.letterSpacing};\n`;
    typeCss += `  --solidigm-type-${k}-text-transform: ${v.textTransform};\n`;
    typeCss += `  --solidigm-type-${k}-text-decoration: ${v.textDecoration};\n`;
  }
  typeCss += '}\n';
  writeFile(path.join(outDir, 'typography.css'), typeCss);

  // index.css
  const indexCss =
    '/* Solidigm Brand Tokens — generated by build.js */\n' +
    "@import './colors.css';\n" +
    "@import './typography.css';\n";
  writeFile(path.join(outDir, 'index.css'), indexCss);
}

// ---------------------------------------------------------------------------
// Generator: SCSS
// ---------------------------------------------------------------------------

function generateSCSS(colors, typography, outDir) {
  // _colors.scss
  let colorsScss = '// Solidigm Brand Color Tokens — generated by build.js\n\n';
  for (const c of colors) {
    colorsScss += `$solidigm-color-${c.kebab}: ${c.hex};\n`;
  }
  colorsScss += '\n$solidigm-colors: (\n';
  for (let i = 0; i < colors.length; i++) {
    const c = colors[i];
    const comma = i < colors.length - 1 ? ',' : '';
    colorsScss += `  '${c.kebab}': $solidigm-color-${c.kebab}${comma}\n`;
  }
  colorsScss += ');\n';
  writeFile(path.join(outDir, '_colors.scss'), colorsScss);

  // _typography.scss
  let typeScss = '// Solidigm Brand Typography Tokens — generated by build.js\n\n';
  for (const t of typography) {
    const k = t.kebab;
    const v = t.value;
    typeScss += `$solidigm-type-${k}-font-family: ${v.fontFamily};\n`;
    typeScss += `$solidigm-type-${k}-font-size: ${v.fontSize};\n`;
    typeScss += `$solidigm-type-${k}-font-weight: ${v.fontWeight};\n`;
    typeScss += `$solidigm-type-${k}-line-height: ${v.lineHeight};\n`;
    typeScss += `$solidigm-type-${k}-letter-spacing: ${v.letterSpacing};\n`;
    typeScss += `$solidigm-type-${k}-text-transform: ${v.textTransform};\n`;
    typeScss += `$solidigm-type-${k}-text-decoration: ${v.textDecoration};\n\n`;
  }
  typeScss += '$solidigm-type: (\n';
  for (let i = 0; i < typography.length; i++) {
    const t = typography[i];
    const k = t.kebab;
    const comma = i < typography.length - 1 ? ',' : '';
    typeScss += `  '${k}': (\n`;
    typeScss += `    'font-family': $solidigm-type-${k}-font-family,\n`;
    typeScss += `    'font-size': $solidigm-type-${k}-font-size,\n`;
    typeScss += `    'font-weight': $solidigm-type-${k}-font-weight,\n`;
    typeScss += `    'line-height': $solidigm-type-${k}-line-height,\n`;
    typeScss += `    'letter-spacing': $solidigm-type-${k}-letter-spacing,\n`;
    typeScss += `    'text-transform': $solidigm-type-${k}-text-transform,\n`;
    typeScss += `    'text-decoration': $solidigm-type-${k}-text-decoration\n`;
    typeScss += `  )${comma}\n`;
  }
  typeScss += ');\n';
  writeFile(path.join(outDir, '_typography.scss'), typeScss);

  // _index.scss
  const indexScss =
    "// Solidigm Brand Tokens — generated by build.js\n" +
    "@forward 'colors';\n" +
    "@forward 'typography';\n";
  writeFile(path.join(outDir, '_index.scss'), indexScss);
}

// ---------------------------------------------------------------------------
// Generator: JavaScript (ESM + CJS + TypeScript defs)
// ---------------------------------------------------------------------------

function generateJS(colors, typography, outDir) {
  // Build colors object literal string
  const colorEntries = colors
    .map((c) => `  ${c.camel}: '${c.hex}'`)
    .join(',\n');

  // Build typography object with desktop/mobile groups
  function buildTypeGroup(group, styles) {
    const entries = styles
      .map((t) => {
        const v = t.value;
        return [
          `    ${t.camel}: {`,
          `      fontFamily: '${v.fontFamily}',`,
          `      fontSize: '${v.fontSize}',`,
          `      fontWeight: ${v.fontWeight},`,
          `      lineHeight: '${v.lineHeight}',`,
          `      letterSpacing: '${v.letterSpacing}',`,
          `      textTransform: '${v.textTransform}',`,
          `      textDecoration: '${v.textDecoration}'`,
          `    }`,
        ].join('\n');
      })
      .join(',\n');
    return `  ${group}: {\n${entries}\n  }`;
  }

  const desktopStyles = typography.filter((t) => t.group === 'Desktop');
  const mobileStyles = typography.filter((t) => t.group === 'Mobile');

  const typeObj =
    buildTypeGroup('desktop', desktopStyles) +
    ',\n' +
    buildTypeGroup('mobile', mobileStyles);

  // index.mjs (ESM)
  const esm =
    '// Solidigm Brand Tokens — generated by build.js\n\n' +
    `export const colors = {\n${colorEntries}\n};\n\n` +
    `export const typography = {\n${typeObj}\n};\n`;
  writeFile(path.join(outDir, 'index.mjs'), esm);

  // index.js (CJS)
  const cjs =
    '// Solidigm Brand Tokens — generated by build.js\n' +
    "'use strict';\n\n" +
    `const colors = {\n${colorEntries}\n};\n\n` +
    `const typography = {\n${typeObj}\n};\n\n` +
    'module.exports = { colors, typography };\n';
  writeFile(path.join(outDir, 'index.js'), cjs);

  // index.d.ts (TypeScript)
  const colorTypeEntries = colors
    .map((c) => `  readonly ${c.camel}: '${c.hex}';`)
    .join('\n');

  function buildDtsTypeGroup(group, styles) {
    const entries = styles
      .map((t) => {
        const v = t.value;
        return [
          `    readonly ${t.camel}: {`,
          `      readonly fontFamily: '${v.fontFamily}';`,
          `      readonly fontSize: '${v.fontSize}';`,
          `      readonly fontWeight: ${v.fontWeight};`,
          `      readonly lineHeight: '${v.lineHeight}';`,
          `      readonly letterSpacing: '${v.letterSpacing}';`,
          `      readonly textTransform: '${v.textTransform}';`,
          `      readonly textDecoration: '${v.textDecoration}';`,
          `    };`,
        ].join('\n');
      })
      .join('\n');
    return `  readonly ${group}: {\n${entries}\n  };`;
  }

  const dts =
    '// Solidigm Brand Tokens — generated by build.js\n\n' +
    `export declare const colors: {\n${colorTypeEntries}\n};\n\n` +
    'export declare const typography: {\n' +
    buildDtsTypeGroup('desktop', desktopStyles) +
    '\n' +
    buildDtsTypeGroup('mobile', mobileStyles) +
    '\n};\n';
  writeFile(path.join(outDir, 'index.d.ts'), dts);
}

// ---------------------------------------------------------------------------
// Generator: JSON (W3C DTCG format)
// ---------------------------------------------------------------------------

function generateJSON(colorsRaw, typographyRaw, outDir) {
  // colors.json — preserve group structure, skip gradient
  const colorsOut = {};
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    colorsOut[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      colorsOut[group][name] = {
        $type: token.$type,
        $value: token.$value,
      };
    }
  }
  writeFile(path.join(outDir, 'colors.json'), JSON.stringify(colorsOut, null, 2) + '\n');

  // typography.json — preserve group structure
  const typeOut = {};
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    typeOut[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      typeOut[group][name] = {
        $type: token.$type,
        $value: { ...token.$value },
      };
    }
  }
  writeFile(path.join(outDir, 'typography.json'), JSON.stringify(typeOut, null, 2) + '\n');

  // index.json — combined
  const combined = {
    color: colorsOut,
    typography: typeOut,
  };
  writeFile(path.join(outDir, 'index.json'), JSON.stringify(combined, null, 2) + '\n');
}

// ---------------------------------------------------------------------------
// Generator: Tailwind preset
// ---------------------------------------------------------------------------

function generateTailwind(colors, typography, outDir) {
  const colorMap = {};
  for (const c of colors) {
    colorMap[c.kebab] = c.hex;
  }

  const fontSizeMap = {};
  for (const t of typography) {
    const v = t.value;
    fontSizeMap[t.kebab] = [
      v.fontSize,
      {
        lineHeight: v.lineHeight,
        letterSpacing: v.letterSpacing,
        fontWeight: String(v.fontWeight),
      },
    ];
  }

  const preset = {
    theme: {
      extend: {
        colors: colorMap,
        fontFamily: {
          sora: ['Sora', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        },
        fontSize: fontSizeMap,
      },
    },
  };

  const content =
    '// Solidigm Brand Tailwind Preset — generated by build.js\n' +
    'module.exports = ' +
    JSON.stringify(preset, null, 2) +
    ';\n';
  writeFile(path.join(outDir, 'preset.js'), content);
}

// ---------------------------------------------------------------------------
// Generator: Figma / Token Studio format
// ---------------------------------------------------------------------------

function generateFigma(colorsRaw, typographyRaw, outDir) {
  const figma = {
    color: {},
    typography: {},
  };

  // Colors — preserve group structure
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    figma.color[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      figma.color[group][name] = {
        value: token.$value,
        type: 'color',
      };
    }
  }

  // Typography — preserve group structure
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    figma.typography[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      figma.typography[group][name] = {
        value: {
          fontFamily: token.$value.fontFamily,
          fontSize: token.$value.fontSize,
          fontWeight: String(token.$value.fontWeight),
          lineHeight: token.$value.lineHeight,
          letterSpacing: token.$value.letterSpacing,
          textTransform: token.$value.textTransform,
          textDecoration: token.$value.textDecoration,
        },
        type: 'typography',
      };
    }
  }

  writeFile(path.join(outDir, 'tokens.json'), JSON.stringify(figma, null, 2) + '\n');
}

// ---------------------------------------------------------------------------
// Generator: UI Toolkit (combined CSS — tokens + components + utilities)
// ---------------------------------------------------------------------------

/**
 * Generates dist/ui-toolkit.min.css — a single minified CSS file combining:
 *   1. Token-derived custom properties (colors, typography, spacing, radii)
 *   2. Base element resets & heading styles
 *   3. .tk-* component classes (buttons, etc.)
 *   4. .u-* utility classes (layout, text, spacing, responsive)
 *
 * Tokens (layer 1) are generated from source data; layers 2–4 are static
 * rules that reference the custom properties. When a new token category is
 * added (spacing, shadows, etc.) add it to layer 1.
 */
function generateUIToolkit(colors, typography, { spaceRaw, radiusRaw, iconsRaw }, outDir) {
  // --- Layer 1: Custom properties from tokens ---
  const colorVars = colors
    .map((c) => `--solidigm-color-${c.kebab}:${c.hex}`)
    .join(';');

  // Map kebab names to shorter aliases matching the hand-authored toolkit
  const colorAliases = [];
  for (const c of colors) {
    // Derive an alias family (e.g. "purple-500", "neutral-800")
    const k = c.kebab;
    colorAliases.push(`--color-${k}:${c.hex}`);
  }

  const typeVars = typography
    .map((t) => {
      const k = t.kebab;
      const v = t.value;
      return [
        `--solidigm-type-${k}-font-family:${v.fontFamily}`,
        `--solidigm-type-${k}-font-size:${v.fontSize}`,
        `--solidigm-type-${k}-font-weight:${v.fontWeight}`,
        `--solidigm-type-${k}-line-height:${v.lineHeight}`,
        `--solidigm-type-${k}-letter-spacing:${v.letterSpacing}`,
      ].join(';');
    })
    .join(';');

  // --- Token-derived custom properties ---

  // Spacing: generated from tokens/space.json
  const spaceScale = spaceRaw.space || {};
  const spaceVarParts = Object.entries(spaceScale)
    .filter(([, v]) => v && v.$value !== undefined)
    .map(([step, v]) => `--space-${step}:${v.$value}`);

  // Border-radius: generated from tokens/radius.json
  const radiusScale = radiusRaw.radius || {};
  const radiusVarParts = Object.entries(radiusScale)
    .filter(([, v]) => v && v.$value !== undefined)
    .map(([name, v]) => `--border-radius-${name}:${v.$value}`);

  // Icon sizes: generated from tokens/icons.json
  const iconSizeScale = (iconsRaw.icon || {}).size || {};
  const iconSizeVarParts = Object.entries(iconSizeScale)
    .filter(([, v]) => v && v.$value !== undefined)
    .map(([name, v]) => `--icon-size-${name}:${v.$value}`);

  // Static vars that do NOT yet have a token file (typography weights, fluid
  // type scales, button defaults). These are kept here intentionally until a
  // dedicated token category exists for each.
  const staticVarParts = [
    '--font-family-primary:Sora,sans-serif',
    '--font-weight-extralight:200',
    '--font-weight-light:300',
    '--font-weight-regular:400',
    '--font-weight-medium:500',
    '--font-weight-semibold:600',
    '--font-weight-bold:700',
    '--fluid-hero:clamp(42px,5.8vw,112px)',
    '--lh-fluid-hero:clamp(48px,5.7vw,110px)',
    '--fluid-h1:clamp(32px,4.5vw,72px)',
    '--lh-fluid-h1:clamp(38px,4.3vw,82px)',
    '--fluid-h2:clamp(28px,3.9vw,62px)',
    '--lh-fluid-h2:clamp(34px,3.8vw,72px)',
    '--fluid-h3:clamp(24px,2.6vw,42px)',
    '--lh-fluid-h3:clamp(28px,2.5vw,48px)',
    '--fluid-h4:32px', '--lh-fluid-h4:38px',
    '--fluid-h5:24px', '--lh-fluid-h5:28px',
    '--fluid-h6:20px', '--lh-fluid-h6:26px',
    '--button-padding-y:16px',
    '--button-padding-x:28px',
    '--button-min-width:225px',
  ];

  const staticVars = [
    ...spaceVarParts,
    ...radiusVarParts,
    ...iconSizeVarParts,
    ...staticVarParts,
  ].join(';');

  const rootBlock = `:root{${colorVars};${colorAliases.join(';')};${typeVars};${staticVars}}`;

  // Responsive token overrides
  const responsiveRoot = '@media (min-width:992px){:root{--button-padding-y:18px;--button-min-width:276px}}';

  // --- Layer 2: Base element styles ---
  const baseStyles = [
    '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}',
    'html{font-size:100%}',
    'body{font-family:var(--font-family-primary);font-weight:var(--font-weight-regular);color:var(--color-neutral-800,#21201f);line-height:1.5;-webkit-font-smoothing:antialiased}',
    'h1,h2,h3,h4,h5,h6{font-weight:var(--font-weight-extralight);color:var(--color-purple-600,#2f006b);line-height:1.2;margin-top:var(--space-8);margin-bottom:var(--space-4)}',
    'h1{font-size:var(--fluid-h1);line-height:var(--lh-fluid-h1)}',
    'h2{font-size:var(--fluid-h2);line-height:var(--lh-fluid-h2)}',
    'h3{font-size:var(--fluid-h3);line-height:var(--lh-fluid-h3)}',
    'h4{font-size:var(--fluid-h4);line-height:var(--lh-fluid-h4)}',
    'h5{font-size:var(--fluid-h5);line-height:var(--lh-fluid-h5)}',
    'h6{font-size:var(--fluid-h6);line-height:var(--lh-fluid-h6)}',
  ].join('');

  // --- Layer 3: Component classes (.tk-*) ---
  const componentClasses = [
    '.tk-btn{padding:var(--button-padding-y) var(--button-padding-x);min-width:var(--button-min-width);border-radius:var(--border-radius-sm);font-size:16px;font-weight:var(--font-weight-medium);cursor:pointer;text-align:center;transition:background-color 0.2s,box-shadow 0.2s,color 0.2s;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;border:1px solid transparent}',
    '.tk-btn--primary{background-color:var(--color-solidigm-purple,#4f00b5);color:#fff}',
    '.tk-btn--primary:hover{background-color:var(--color-purple-600,#2f006b)}',
    '.tk-btn--secondary{background-color:#fff;color:var(--color-solidigm-purple,#4f00b5);border-color:var(--color-solidigm-purple,#4f00b5)}',
    '.tk-btn--secondary:hover{background-color:var(--color-neutral-50,#f4f3f1)}',
  ].join('');

  // --- Layer 4: Utility classes (.u-*) ---
  const utilityClasses = [
    // Color
    '.u-text-primary{color:var(--color-solidigm-purple,#4f00b5) !important}',
    '.u-text-white{color:#fff !important}',
    '.u-bg-primary{background-color:var(--color-solidigm-purple,#4f00b5) !important}',
    '.u-bg-neutral{background-color:var(--color-neutral-50,#f4f3f1) !important}',
    // Text
    '.u-text-center{text-align:center !important}',
    '.u-text-right{text-align:right !important}',
    '.u-font-bold{font-weight:var(--font-weight-bold) !important}',
    '.u-font-medium{font-weight:var(--font-weight-medium) !important}',
    '.u-text-caption{font-size:16px;line-height:20px}',
    '.u-text-xs{font-size:12px !important}',
    '.u-text-sm{font-size:14px !important}',
    '.u-text-base{font-size:16px !important}',
    '.u-text-lg{font-size:18px !important}',
    '.u-text-xl{font-size:20px !important}',
    '.u-uppercase{text-transform:uppercase !important}',
    '.u-lowercase{text-transform:lowercase !important}',
    '.u-no-underline{text-decoration:none !important}',
    // Spacing
    '.u-p-4{padding:var(--space-4) !important}',
    '.u-m-4{margin:var(--space-4) !important}',
    '.u-p-8{padding:var(--space-8) !important}',
    '.u-m-8{margin:var(--space-8) !important}',
    '.u-p-16{padding:var(--space-16) !important}',
    '.u-m-16{margin:var(--space-16) !important}',
    '.u-mb-0{margin-bottom:0 !important}',
    '.u-mt-0{margin-top:0 !important}',
    '.u-mt-auto{margin-top:auto !important}',
    '.u-ml-auto{margin-left:auto !important}',
    '.u-mr-auto{margin-right:auto !important}',
    '.u-mx-auto{margin-left:auto !important;margin-right:auto !important}',
    '.u-round-md{border-radius:var(--border-radius-md) !important}',
    // Layout
    '.u-flex{display:flex !important}',
    '.u-inline-flex{display:inline-flex !important}',
    '.u-block{display:block !important}',
    '.u-inline-block{display:inline-block !important}',
    '.u-hidden{display:none !important}',
    '.u-relative{position:relative !important}',
    '.u-absolute{position:absolute !important}',
    '.u-items-center{align-items:center !important}',
    '.u-justify-center{justify-content:center !important}',
    '.u-justify-between{justify-content:space-between !important}',
    '.u-flex-col{flex-direction:column !important}',
    '.u-flex-wrap{flex-wrap:wrap !important}',
    // Sizing
    '.u-w-full{width:100% !important}',
    '.u-h-full{height:100% !important}',
    '.u-max-w-screen{max-width:1920px !important}',
    // Responsive
    '@media (max-width:767px){.u-hidden-mobile{display:none !important}}',
    '@media (min-width:768px){.u-hidden-desktop{display:none !important}}',
    // Interactivity
    '.u-transition{transition:all 0.2s ease !important}',
    '.u-hover-scale:hover{transform:scale(1.02) !important}',
  ].join('');

  // --- Assemble ---
  const fontImport = "@import url('https://fonts.googleapis.com/css2?family=Sora:wght@200..700&display=swap');";
  const banner = `/*! Solidigm UI Toolkit — generated by build.js on ${new Date().toISOString().slice(0, 10)} */`;

  const css = [
    banner,
    fontImport,
    rootBlock,
    responsiveRoot,
    baseStyles,
    componentClasses,
    utilityClasses,
  ].join('');

  writeFile(path.join(outDir, 'ui-toolkit.min.css'), css);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log('Building @solidigm/brand-tokens...\n');

  const {
    colorsRaw, typographyRaw, spaceRaw, breakpointsRaw, radiusRaw,
    shapeRaw, motionRaw, elevationRaw, iconsRaw, semanticRaw,
  } = readSourceTokens();
  const colors = transformColors(colorsRaw);
  const typography = transformTypography(typographyRaw);

  console.log(`  Found ${colors.length} color tokens`);
  console.log(`  Found ${typography.length} typography tokens\n`);

  const root = __dirname;

  // CSS
  generateCSS(colors, typography, path.join(root, 'dist', 'css'));

  // SCSS
  generateSCSS(colors, typography, path.join(root, 'dist', 'scss'));

  // JS / TS
  generateJS(colors, typography, path.join(root, 'dist', 'js'));

  // JSON (W3C DTCG) — generate a unified index of all token categories
  const combined = {
    color:       colorsRaw,
    typography:  typographyRaw,
    space:       spaceRaw,
    breakpoints: breakpointsRaw,
    radius:      radiusRaw,
    shape:       shapeRaw,
    motion:      motionRaw,
    elevation:   elevationRaw,
    icons:       iconsRaw,
    semantic:    semanticRaw,
  };
  writeFile(path.join(root, 'tokens', 'index.json'), JSON.stringify(combined, null, 2) + '\n');

  // Tailwind preset
  generateTailwind(colors, typography, path.join(root, 'tailwind'));

  // Figma / Token Studio
  generateFigma(colorsRaw, typographyRaw, path.join(root, 'figma'));

  // UI Toolkit (combined minified CSS) — passes primitive token data so
  // spacing, radius, and icon-size custom properties are token-derived
  generateUIToolkit(colors, typography, { spaceRaw, radiusRaw, iconsRaw }, path.join(root, 'dist'));

  console.log('\nBuild complete.\n');
}

main();
