#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** "Solidigm Purple" → "solidigm-purple" */
function toKebab(name) {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

/** "Solidigm Purple" → "solidigmPurple", "DT Hero" → "dtHero" */
function toCamel(name) {
  const words = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return words
    .map((w, i) =>
      i === 0
        ? w.toLowerCase()
        : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()
    )
    .join('');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`  ✓ ${path.relative(process.cwd(), filePath)}`);
}

// ---------------------------------------------------------------------------
// Source token readers
// ---------------------------------------------------------------------------

function readSourceTokens() {
  const colorsRaw = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'resources', 'color.styles.tokens.json'), 'utf8')
  );
  const typographyRaw = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'resources', 'text.styles.tokens.json'), 'utf8')
  );
  return { colorsRaw, typographyRaw };
}

// ---------------------------------------------------------------------------
// Transform: colors
// ---------------------------------------------------------------------------

/**
 * Returns a flat array of { name, kebab, camel, hex, group }
 * Skips gradient tokens.
 */
function transformColors(colorsRaw) {
  const colors = [];
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      colors.push({
        name,
        kebab: toKebab(name),
        camel: toCamel(name),
        hex: token.$value,
        group,
      });
    }
  }
  return colors;
}

// ---------------------------------------------------------------------------
// Transform: typography
// ---------------------------------------------------------------------------

/**
 * Returns a flat array of { name, kebab, camel, group, value }
 * where value contains fontFamily, fontSize, fontWeight, letterSpacing,
 * lineHeight, textTransform, textDecoration.
 */
function transformTypography(typographyRaw) {
  const styles = [];
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      styles.push({
        name,
        kebab: toKebab(name),
        camel: toCamel(name),
        group,
        value: { ...token.$value },
      });
    }
  }
  return styles;
}

// ---------------------------------------------------------------------------
// Generator: CSS Custom Properties
// ---------------------------------------------------------------------------

function generateCSS(colors, typography, outDir) {
  // colors.css
  let colorsCss = '/* Solidigm Brand Color Tokens — generated by build.js */\n:root {\n';
  for (const c of colors) {
    colorsCss += `  --solidigm-color-${c.kebab}: ${c.hex};\n`;
  }
  colorsCss += '}\n';
  writeFile(path.join(outDir, 'colors.css'), colorsCss);

  // typography.css
  let typeCss = '/* Solidigm Brand Typography Tokens — generated by build.js */\n:root {\n';
  for (const t of typography) {
    const k = t.kebab;
    const v = t.value;
    typeCss += `  --solidigm-type-${k}-font-family: ${v.fontFamily};\n`;
    typeCss += `  --solidigm-type-${k}-font-size: ${v.fontSize};\n`;
    typeCss += `  --solidigm-type-${k}-font-weight: ${v.fontWeight};\n`;
    typeCss += `  --solidigm-type-${k}-line-height: ${v.lineHeight};\n`;
    typeCss += `  --solidigm-type-${k}-letter-spacing: ${v.letterSpacing};\n`;
    typeCss += `  --solidigm-type-${k}-text-transform: ${v.textTransform};\n`;
    typeCss += `  --solidigm-type-${k}-text-decoration: ${v.textDecoration};\n`;
  }
  typeCss += '}\n';
  writeFile(path.join(outDir, 'typography.css'), typeCss);

  // index.css
  const indexCss =
    '/* Solidigm Brand Tokens — generated by build.js */\n' +
    "@import './colors.css';\n" +
    "@import './typography.css';\n";
  writeFile(path.join(outDir, 'index.css'), indexCss);
}

// ---------------------------------------------------------------------------
// Generator: SCSS
// ---------------------------------------------------------------------------

function generateSCSS(colors, typography, outDir) {
  // _colors.scss
  let colorsScss = '// Solidigm Brand Color Tokens — generated by build.js\n\n';
  for (const c of colors) {
    colorsScss += `$solidigm-color-${c.kebab}: ${c.hex};\n`;
  }
  colorsScss += '\n$solidigm-colors: (\n';
  for (let i = 0; i < colors.length; i++) {
    const c = colors[i];
    const comma = i < colors.length - 1 ? ',' : '';
    colorsScss += `  '${c.kebab}': $solidigm-color-${c.kebab}${comma}\n`;
  }
  colorsScss += ');\n';
  writeFile(path.join(outDir, '_colors.scss'), colorsScss);

  // _typography.scss
  let typeScss = '// Solidigm Brand Typography Tokens — generated by build.js\n\n';
  for (const t of typography) {
    const k = t.kebab;
    const v = t.value;
    typeScss += `$solidigm-type-${k}-font-family: ${v.fontFamily};\n`;
    typeScss += `$solidigm-type-${k}-font-size: ${v.fontSize};\n`;
    typeScss += `$solidigm-type-${k}-font-weight: ${v.fontWeight};\n`;
    typeScss += `$solidigm-type-${k}-line-height: ${v.lineHeight};\n`;
    typeScss += `$solidigm-type-${k}-letter-spacing: ${v.letterSpacing};\n`;
    typeScss += `$solidigm-type-${k}-text-transform: ${v.textTransform};\n`;
    typeScss += `$solidigm-type-${k}-text-decoration: ${v.textDecoration};\n\n`;
  }
  typeScss += '$solidigm-type: (\n';
  for (let i = 0; i < typography.length; i++) {
    const t = typography[i];
    const k = t.kebab;
    const comma = i < typography.length - 1 ? ',' : '';
    typeScss += `  '${k}': (\n`;
    typeScss += `    'font-family': $solidigm-type-${k}-font-family,\n`;
    typeScss += `    'font-size': $solidigm-type-${k}-font-size,\n`;
    typeScss += `    'font-weight': $solidigm-type-${k}-font-weight,\n`;
    typeScss += `    'line-height': $solidigm-type-${k}-line-height,\n`;
    typeScss += `    'letter-spacing': $solidigm-type-${k}-letter-spacing,\n`;
    typeScss += `    'text-transform': $solidigm-type-${k}-text-transform,\n`;
    typeScss += `    'text-decoration': $solidigm-type-${k}-text-decoration\n`;
    typeScss += `  )${comma}\n`;
  }
  typeScss += ');\n';
  writeFile(path.join(outDir, '_typography.scss'), typeScss);

  // _index.scss
  const indexScss =
    "// Solidigm Brand Tokens — generated by build.js\n" +
    "@forward 'colors';\n" +
    "@forward 'typography';\n";
  writeFile(path.join(outDir, '_index.scss'), indexScss);
}

// ---------------------------------------------------------------------------
// Generator: JavaScript (ESM + CJS + TypeScript defs)
// ---------------------------------------------------------------------------

function generateJS(colors, typography, outDir) {
  // Build colors object literal string
  const colorEntries = colors
    .map((c) => `  ${c.camel}: '${c.hex}'`)
    .join(',\n');

  // Build typography object with desktop/mobile groups
  function buildTypeGroup(group, styles) {
    const entries = styles
      .map((t) => {
        const v = t.value;
        return [
          `    ${t.camel}: {`,
          `      fontFamily: '${v.fontFamily}',`,
          `      fontSize: '${v.fontSize}',`,
          `      fontWeight: ${v.fontWeight},`,
          `      lineHeight: '${v.lineHeight}',`,
          `      letterSpacing: '${v.letterSpacing}',`,
          `      textTransform: '${v.textTransform}',`,
          `      textDecoration: '${v.textDecoration}'`,
          `    }`,
        ].join('\n');
      })
      .join(',\n');
    return `  ${group}: {\n${entries}\n  }`;
  }

  const desktopStyles = typography.filter((t) => t.group === 'Desktop');
  const mobileStyles = typography.filter((t) => t.group === 'Mobile');

  const typeObj =
    buildTypeGroup('desktop', desktopStyles) +
    ',\n' +
    buildTypeGroup('mobile', mobileStyles);

  // index.mjs (ESM)
  const esm =
    '// Solidigm Brand Tokens — generated by build.js\n\n' +
    `export const colors = {\n${colorEntries}\n};\n\n` +
    `export const typography = {\n${typeObj}\n};\n`;
  writeFile(path.join(outDir, 'index.mjs'), esm);

  // index.js (CJS)
  const cjs =
    '// Solidigm Brand Tokens — generated by build.js\n' +
    "'use strict';\n\n" +
    `const colors = {\n${colorEntries}\n};\n\n` +
    `const typography = {\n${typeObj}\n};\n\n` +
    'module.exports = { colors, typography };\n';
  writeFile(path.join(outDir, 'index.js'), cjs);

  // index.d.ts (TypeScript)
  const colorTypeEntries = colors
    .map((c) => `  readonly ${c.camel}: '${c.hex}';`)
    .join('\n');

  function buildDtsTypeGroup(group, styles) {
    const entries = styles
      .map((t) => {
        const v = t.value;
        return [
          `    readonly ${t.camel}: {`,
          `      readonly fontFamily: '${v.fontFamily}';`,
          `      readonly fontSize: '${v.fontSize}';`,
          `      readonly fontWeight: ${v.fontWeight};`,
          `      readonly lineHeight: '${v.lineHeight}';`,
          `      readonly letterSpacing: '${v.letterSpacing}';`,
          `      readonly textTransform: '${v.textTransform}';`,
          `      readonly textDecoration: '${v.textDecoration}';`,
          `    };`,
        ].join('\n');
      })
      .join('\n');
    return `  readonly ${group}: {\n${entries}\n  };`;
  }

  const dts =
    '// Solidigm Brand Tokens — generated by build.js\n\n' +
    `export declare const colors: {\n${colorTypeEntries}\n};\n\n` +
    'export declare const typography: {\n' +
    buildDtsTypeGroup('desktop', desktopStyles) +
    '\n' +
    buildDtsTypeGroup('mobile', mobileStyles) +
    '\n};\n';
  writeFile(path.join(outDir, 'index.d.ts'), dts);
}

// ---------------------------------------------------------------------------
// Generator: JSON (W3C DTCG format)
// ---------------------------------------------------------------------------

function generateJSON(colorsRaw, typographyRaw, outDir) {
  // colors.json — preserve group structure, skip gradient
  const colorsOut = {};
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    colorsOut[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      colorsOut[group][name] = {
        $type: token.$type,
        $value: token.$value,
      };
    }
  }
  writeFile(path.join(outDir, 'colors.json'), JSON.stringify(colorsOut, null, 2) + '\n');

  // typography.json — preserve group structure
  const typeOut = {};
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    typeOut[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      typeOut[group][name] = {
        $type: token.$type,
        $value: { ...token.$value },
      };
    }
  }
  writeFile(path.join(outDir, 'typography.json'), JSON.stringify(typeOut, null, 2) + '\n');

  // index.json — combined
  const combined = {
    color: colorsOut,
    typography: typeOut,
  };
  writeFile(path.join(outDir, 'index.json'), JSON.stringify(combined, null, 2) + '\n');
}

// ---------------------------------------------------------------------------
// Generator: Tailwind preset
// ---------------------------------------------------------------------------

function generateTailwind(colors, typography, outDir) {
  const colorMap = {};
  for (const c of colors) {
    colorMap[c.kebab] = c.hex;
  }

  const fontSizeMap = {};
  for (const t of typography) {
    const v = t.value;
    fontSizeMap[t.kebab] = [
      v.fontSize,
      {
        lineHeight: v.lineHeight,
        letterSpacing: v.letterSpacing,
        fontWeight: String(v.fontWeight),
      },
    ];
  }

  const preset = {
    theme: {
      extend: {
        colors: colorMap,
        fontFamily: {
          sora: ['Sora', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        },
        fontSize: fontSizeMap,
      },
    },
  };

  const content =
    '// Solidigm Brand Tailwind Preset — generated by build.js\n' +
    'module.exports = ' +
    JSON.stringify(preset, null, 2) +
    ';\n';
  writeFile(path.join(outDir, 'preset.js'), content);
}

// ---------------------------------------------------------------------------
// Generator: Figma / Token Studio format
// ---------------------------------------------------------------------------

function generateFigma(colorsRaw, typographyRaw, outDir) {
  const figma = {
    color: {},
    typography: {},
  };

  // Colors — preserve group structure
  for (const [group, tokens] of Object.entries(colorsRaw)) {
    figma.color[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'color') continue;
      figma.color[group][name] = {
        value: token.$value,
        type: 'color',
      };
    }
  }

  // Typography — preserve group structure
  for (const [group, tokens] of Object.entries(typographyRaw)) {
    figma.typography[group] = {};
    for (const [name, token] of Object.entries(tokens)) {
      if (token.$type !== 'typography') continue;
      figma.typography[group][name] = {
        value: {
          fontFamily: token.$value.fontFamily,
          fontSize: token.$value.fontSize,
          fontWeight: String(token.$value.fontWeight),
          lineHeight: token.$value.lineHeight,
          letterSpacing: token.$value.letterSpacing,
          textTransform: token.$value.textTransform,
          textDecoration: token.$value.textDecoration,
        },
        type: 'typography',
      };
    }
  }

  writeFile(path.join(outDir, 'tokens.json'), JSON.stringify(figma, null, 2) + '\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log('Building @solidigm/brand-tokens...\n');

  const { colorsRaw, typographyRaw } = readSourceTokens();
  const colors = transformColors(colorsRaw);
  const typography = transformTypography(typographyRaw);

  console.log(`  Found ${colors.length} color tokens`);
  console.log(`  Found ${typography.length} typography tokens\n`);

  const root = __dirname;

  // CSS
  generateCSS(colors, typography, path.join(root, 'dist', 'css'));

  // SCSS
  generateSCSS(colors, typography, path.join(root, 'dist', 'scss'));

  // JS / TS
  generateJS(colors, typography, path.join(root, 'dist', 'js'));

  // JSON (W3C DTCG)
  generateJSON(colorsRaw, typographyRaw, path.join(root, 'tokens'));

  // Tailwind preset
  generateTailwind(colors, typography, path.join(root, 'tailwind'));

  // Figma / Token Studio
  generateFigma(colorsRaw, typographyRaw, path.join(root, 'figma'));

  console.log('\nBuild complete.\n');
}

main();
